name: code-checkout-example

on:
  workflow_dispatch: 
env:
  APP_NAME: Dev

jobs:
  code-checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: code-checkout
        uses: actions/checkout@v4
      - name: Connecting to env
        run: echo env is $APP_NAME
          
       
