name: code-checkout-example

on:
  workflow_dispatch: 
    inputs:
      environment:
        description: Choose the environment to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - stage
          - prod
      artifact_tag:
        description: Choose the git_tag to deploy
        required: true
        
env:
  APP_NAME: Dev

jobs:
  code-checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: code-checkout
        uses: actions/checkout@v4
      - name: Connecting to env
        run: echo env is $APP_NAME
      - name: deploy the app
        run: echo Deploying the ${{inputs.artifact_tag}} application to ${{inputs.environment}}
          
       
