name: multi-job workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: hi
        run: echo hi
  second-job:
    runs-on: ubuntu-24.04
    steps:
      - name: hello
        run: echo hello
    
