name: multi-job workflow

on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: building
        run: |
          echo Image Built
          sleep 3600
        
  Test:
    needs: Build
    runs-on: ubuntu-24.04
    steps:
      - name: testing
        run: |
          echo tested the application
          sleep 3600
        
  Deploy:
    needs: Test
    runs-on: ubuntu-slim
    steps:
      - name: Deploying
        run: echo deployed
