name: multi-job workflow

on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: building
        run: echo Image Built
  Test:
    runs-on: ubuntu-24.04
    steps:
      - name: testing
        run: echo tested the application
  Deploy:
    runs-on: ubuntu-slim
    steps:
      - name: Deploying
        run: echo deployed
